[package]
description = "A simple webserver written in Rust that displays a Hello World webpage."
edition = "2021"
name = "hello-world-server"
version = "0.0.1"

[dependencies]
actix-web = "4.3"
actix-files = "0.6.2"
log = "0.4.0"
env_logger = "0.9.0"
